#!/usr/bin/env node
/**
 * Regenerates references/ from two sources of truth:
 *   - the Profolio codebase (routes, tenant flags, components, tokens)
 *   - the design canvas prose (component descriptions and variants)
 *
 * Hand-written files are never touched: references/tenants/*, references/pages/_shell.md,
 * references/flows/*. Everything this script emits carries a GENERATED banner.
 *
 * Usage:  node scripts/build.mjs --repo ../profolio-reactjs-copy
 */

import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execSync } from 'node:child_process';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const REFS = join(ROOT, 'references');
const CANVAS = join(ROOT, 'canvas');

const argRepo = process.argv.indexOf('--repo');
const REPO = argRepo > -1 ? process.argv[argRepo + 1] : join(ROOT, '..', 'profolio-reactjs-copy');
if (!existsSync(REPO)) {
  console.error(`profolio repo not found at ${REPO} — pass --repo <path>`);
  process.exit(1);
}

const read = (p) => (existsSync(p) ? readFileSync(p, 'utf8') : '');
const sh = (cmd, cwd) => { try { return execSync(cmd, { cwd, encoding: 'utf8' }).trim(); } catch { return ''; } };

const SOURCE_SHA = sh('git rev-parse --short HEAD', REPO) || 'unknown';
const STAMP = `<!-- GENERATED by scripts/build.mjs from profolio-reactjs@${SOURCE_SHA} — do not edit by hand -->`;

const write = (rel, body) => {
  const p = join(REFS, rel);
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, `${STAMP}\n\n${body.trim()}\n`);
  return Buffer.byteLength(body);
};

/* ── decode the few HTML entities that appear in canvas prose ─────────────── */
const ENTITIES = { amp: '&', lt: '<', gt: '>', quot: '"', '#39': "'", nbsp: ' ', times: '×', middot: '·', ndash: '–', mdash: '—', hellip: '…', rarr: '→', le: '≤', ge: '≥', deg: '°' };
const decode = (s) => s.replace(/&(#?\w+);/g, (m, e) => ENTITIES[e] ?? m);

/* Strip tags but keep <code> contents fenced, so token and prop names survive. */
const textOf = (html) =>
  decode(
    html
      .replace(/<code[^>]*>(.*?)<\/code>/gis, (_, c) => '`' + c.replace(/<[^>]*>/g, '') + '`')
      .replace(/<br\s*\/?>/gi, ' ')
      .replace(/<[^>]+>/g, ' ')
  )
    .replace(/\s+/g, ' ')
    .trim();

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

/* ─────────────────────────────────────────────────────────────────────────────
   1. COMPONENTS — from canvas prose
   Each <section id="x"> is one entry: <h2> name, <p> description + props,
   <h3> variant-group headings. Rendered specimens are dropped.
   ───────────────────────────────────────────────────────────────────────── */
const LAYERS = [
  ['Bayut Profolio Atoms.dc.html', 'atom'],
  ['Bayut Profolio Molecules.dc.html', 'molecule'],
  ['Bayut Profolio Organisms.dc.html', 'organism'],
];

const components = [];
for (const [file, layer] of LAYERS) {
  const html = read(join(CANVAS, file));
  if (!html) { console.warn(`canvas file missing: ${file}`); continue; }

  for (const m of html.matchAll(/<section\s+id="([^"]+)"[^>]*>([\s\S]*?)<\/section>/gi)) {
    const [, id, inner] = m;

    const h2 = inner.match(/<h2[^>]*>([\s\S]*?)<\/h2>/i);
    if (!h2) continue;                                   // nav blocks carry no h2
    const name = textOf(h2[1]);
    if (!name || name.length > 60) continue;

    // paragraphs directly describing the component, before the first specimen card
    const paras = [...inner.matchAll(/<p[^>]*>([\s\S]*?)<\/p>/gi)]
      .map((p) => textOf(p[1]))
      .filter((t) => t.length > 25);

    const variants = [...inner.matchAll(/<h3[^>]*>([\s\S]*?)<\/h3>/gi)]
      .map((h) => textOf(h[1]))
      .filter(Boolean);

    // first backticked path that looks like a source file
    const srcHit = inner.match(/<code[^>]*>([^<]*\/[^<]*\.js)<\/code>/i);

    components.push({
      id, name, layer,
      source: srcHit ? srcHit[1] : '',
      description: paras[0] || '',
      notes: paras.slice(1),
      variants,
    });
  }
}

/* ─────────────────────────────────────────────────────────────────────────────
   2. USAGE — which barrel exports are actually imported anywhere
   ───────────────────────────────────────────────────────────────────────── */
const barrel = read(join(REPO, 'src/components/common/index.js'));
const exported = [...barrel.matchAll(/export\s*\{([^}]*)\}/g)]
  .flatMap((m) => m[1].split(','))
  .map((x) => x.replace(/default\s+as\s+/, '').trim())
  .filter((x) => /^[A-Z]/.test(x));

const srcFiles = [];
(function walk(dir) {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) walk(p);
    else if (e.name.endsWith('.js')) srcFiles.push(p);
  }
})(join(REPO, 'src'));

const corpus = srcFiles
  .filter((p) => !p.includes('/components/common/index.js'))
  .map((p) => read(p))
  .join('\n');

const usage = Object.fromEntries(
  exported.map((n) => [n, new RegExp(`\\b${n}\\b`).test(corpus) ? 'used' : 'unreferenced'])
);

/* ─────────────────────────────────────────────────────────────────────────────
   3. ROUTES
   ───────────────────────────────────────────────────────────────────────── */
const routeSrc = ['src/tenant/bayut/routes', 'src/tenant/common/routes']
  .flatMap((d) => {
    const dir = join(REPO, d);
    return existsSync(dir) ? readdirSync(dir).map((f) => read(join(dir, f))) : [];
  })
  .join('\n');

const routes = [...new Set([...routeSrc.matchAll(/path:\s*['"`]([^'"`]+)/g)].map((m) => m[1]))]
  .map((r) => r.replace('${path}', ''))
  .filter((r) => r && r !== '/')
  .sort();

const pageDirs = existsSync(join(REPO, 'src/container/pages'))
  ? readdirSync(join(REPO, 'src/container/pages'), { withFileTypes: true })
      .filter((e) => e.isDirectory()).map((e) => e.name)
  : [];

/* Match a route to the page directory that most likely renders it. */
const SPELLING = { 'agency-staff': 'agancy-staff', 'listings': 'listings', 'packages': 'prop-shop', 'signin': 'authentication' };
const pageFor = (route) => {
  const seg = route.split('/').filter(Boolean)[0] || '';
  if (SPELLING[seg] && pageDirs.includes(SPELLING[seg])) return SPELLING[seg];
  const norm = (s) => s.replace(/[^a-z]/g, '');
  return pageDirs.find((d) => norm(d) === norm(seg))
      || pageDirs.find((d) => norm(d).startsWith(norm(seg)) && seg.length > 3)
      || '';
};

/* ─────────────────────────────────────────────────────────────────────────────
   4. TENANT FLAGS
   ───────────────────────────────────────────────────────────────────────── */
const flagSrc = read(join(REPO, 'src/tenant/bayut/constants/constants.js'));
const flags = [...flagSrc.matchAll(/^\s{2}([A-Z][A-Z0-9_]{2,}):\s*(.+?),?\s*$/gm)]
  .map(([, k, v]) => ({ key: k, value: v.replace(/,$/, '').slice(0, 60) }));

/* Which files reference each flag — tells a designer what a flag changes. */
const flagSurfaces = Object.fromEntries(
  flags.map((f) => {
    const hits = srcFiles
      .filter((p) => new RegExp(`\\b${f.key}\\b`).test(read(p)))
      .map((p) => p.replace(REPO + '/', ''))
      .filter((p) => !/tenant\/[a-z]+\/constants/.test(p));
    return [f.key, hits.slice(0, 3)];
  })
);

/* ─────────────────────────────────────────────────────────────────────────────
   5. TOKENS
   ───────────────────────────────────────────────────────────────────────── */
const themeSrc = read(join(REPO, 'src/theme/index.js'));
const tokens = [...themeSrc.matchAll(/^\s{2}([a-zA-Z][a-zA-Z0-9]*):\s*'([^']+)'/gm)]
  .map(([, k, v]) => ({ key: k, value: v }));

const lessDirs = ['style.less', 'utils.less', 'antd-customized.less'].map((f) =>
  join(REPO, 'src/static/less', f)
);
const lessAll = lessDirs.map(read).join('\n');
const breakpoints = [...new Set([...lessAll.matchAll(/(?:max|min)-width:\s*(\d+)px/g)].map((m) => +m[1]))]
  .sort((a, b) => a - b);

/* ─────────────────────────────────────────────────────────────────────────────
   EMIT
   ───────────────────────────────────────────────────────────────────────── */
for (const d of ['components']) rmSync(join(REFS, d), { recursive: true, force: true });

const sizes = {};

// components/index.md ────────────────────────────────────────────────────────
sizes['components/index.md'] = write(
  'components/index.md',
  `# Component register

${components.length} entries. Load \`components/<id>.md\` for the one you need — never the whole folder,
and never the files in \`canvas/\`.

Design name is canonical. \`source\` is provenance for a developer, not something to fetch.

| Design name | id | Layer | Source | Status |
|---|---|---|---|---|
${components
  .map((c) => {
    const st = usage[c.name.replace(/\s+/g, '')] || usage[c.name] || '';
    return `| ${c.name} | \`${c.id}\` | ${c.layer} | ${c.source ? '`' + c.source + '`' : '—'} | ${st || 'n/a'} |`;
  })
  .join('\n')}

## Unreferenced exports

These barrel exports are never imported outside \`src/components/common/\`. Verify before
spending effort on them — "unreferenced" can also mean newly added or used dynamically.

${exported.filter((n) => usage[n] === 'unreferenced').map((n) => `- \`${n}\``).join('\n') || '- none'}
`
);

// components/<id>.md ────────────────────────────────────────────────────────
for (const c of components) {
  sizes[`components/${c.id}.md`] = write(
    `components/${c.id}.md`,
    `# ${c.name}

- **layer** ${c.layer}
- **source** ${c.source ? '`' + c.source + '`' : '—'}
- **status** ${usage[c.name.replace(/\s+/g, '')] || 'n/a'}

${c.description}

${c.notes.length ? '\n' + c.notes.map((n) => `> ${n}`).join('\n\n') + '\n' : ''}
${c.variants.length ? `## Variants documented\n\n${c.variants.map((v) => `- ${v}`).join('\n')}` : ''}
`
  );
}

// pages/index.md ────────────────────────────────────────────────────────────
sizes['pages/index.md'] = write(
  'pages/index.md',
  `# Screen map

${routes.length} routes. Every screen inherits \`pages/_shell.md\` unless its own file says otherwise.

A PRD names a screen in design language. Match on that; cite the repo path.
No match → ask the designer whether to remake it or receive it. Never improvise.

**Templates marked \`not written\` do not exist yet.** Do not try to load them. For those
screens you have the shell, the route, the page source and the component register — say
that plainly, propose a composition from \`components/index.md\`, and get it approved
before designing. Never pretend a template was read.

| Route | Page source | Template |
|---|---|---|
${routes
  .map((r) => {
    const p = pageFor(r);
    const tpl = `pages/${slug(r)}.md`;
    const exists = existsSync(join(REFS, tpl));
    const t = exists ? `\`${tpl}\`` : '**not written**';
    return `| \`${r}\` | ${p ? '`src/container/pages/' + p + '`' : '—'} | ${t} |`;
  })
  .join('\n')}
`
);

// flags.md ──────────────────────────────────────────────────────────────────
sizes['flags.md'] = write(
  'flags.md',
  `# KSA tenant flags

${flags.length} constants from \`src/tenant/bayut/constants/constants.js\`. These define what
Profolio KSA *is*. A flag that is false removes or changes a surface — check before designing it.

| Flag | Value | Referenced in |
|---|---|---|
${flags
  .map((f) => `| \`${f.key}\` | \`${f.value}\` | ${(flagSurfaces[f.key] || []).map((s) => '`' + s + '`').join(' ') || '—'} |`)
  .join('\n')}
`
);

// foundations.md ────────────────────────────────────────────────────────────
sizes['foundations.md'] = write(
  'foundations.md',
  `# Foundations

Cite token names, not hex values. The cascade resolves in three layers, last wins:
\`src/theme/index.js\` → styled-components → \`src/static/less/style.less\`.

## Tokens

| Token | Value |
|---|---|
${tokens.map((t) => `| \`${t.key}\` | \`${t.value}\` |`).join('\n')}

## Breakpoints in use

${breakpoints.join(' · ')} px

Inconsistent by inheritance — 991/992, 767/768, 575/576 and 479/480 all appear. Until a
canonical scale is agreed, match the value already used by the surface you are changing.
`
);

/* report ------------------------------------------------------------------- */
const total = Object.values(sizes).reduce((a, b) => a + b, 0);
console.log(`source            profolio-reactjs@${SOURCE_SHA}`);
console.log(`components        ${components.length}`);
console.log(`routes            ${routes.length}`);
console.log(`flags             ${flags.length}`);
console.log(`tokens            ${tokens.length}`);
console.log(`unreferenced      ${exported.filter((n) => usage[n] === 'unreferenced').length}`);
console.log(`files written     ${Object.keys(sizes).length}`);
console.log(`generated bytes   ${total} (~${Math.round(total / 4)} tokens if all loaded at once)`);
const perComp = components.length
  ? Math.round(components.reduce((a, c) => a + (sizes[`components/${c.id}.md`] || 0), 0) / components.length)
  : 0;
console.log(`avg component     ${perComp} bytes (~${Math.round(perComp / 4)} tokens)`);
