#!/usr/bin/env node
/**
 * Regenerates references/ from two sources of truth:
 *   - the Profolio codebase (routes, tenant flags, components, tokens)
 *   - the design canvas prose (component descriptions and variants)
 *
 * Hand-written files are never touched: references/tenants/*, references/pages/_shell.md,
 * references/flows/*. Everything this script emits carries a GENERATED banner.
 *
 * Usage:  node scripts/build.mjs --repo ../profolio-reactjs-copy
 */

import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execSync } from 'node:child_process';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const REFS = join(ROOT, 'references');
const CANVAS = join(ROOT, 'canvas');

const argRepo = process.argv.indexOf('--repo');
const REPO = argRepo > -1 ? process.argv[argRepo + 1] : join(ROOT, '..', 'profolio-reactjs-copy');
if (!existsSync(REPO)) {
  console.error(`profolio repo not found at ${REPO} — pass --repo <path>`);
  process.exit(1);
}

const read = (p) => (existsSync(p) ? readFileSync(p, 'utf8') : '');
const sh = (cmd, cwd) => { try { return execSync(cmd, { cwd, encoding: 'utf8' }).trim(); } catch { return ''; } };

const SOURCE_SHA = sh('git rev-parse --short HEAD', REPO) || 'unknown';
const STAMP = `<!-- GENERATED by scripts/build.mjs from profolio-reactjs@${SOURCE_SHA} — do not edit by hand -->`;

const write = (rel, body) => {
  const p = join(REFS, rel);
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, `${STAMP}\n\n${body.trim()}\n`);
  return Buffer.byteLength(body);
};

/* ── decode the few HTML entities that appear in canvas prose ─────────────── */
const ENTITIES = { amp: '&', lt: '<', gt: '>', quot: '"', '#39': "'", nbsp: ' ', times: '×', middot: '·', ndash: '–', mdash: '—', hellip: '…', rarr: '→', le: '≤', ge: '≥', deg: '°' };
const decode = (s) => s.replace(/&(#?\w+);/g, (m, e) => ENTITIES[e] ?? m);

/* Strip tags but keep <code> contents fenced, so token and prop names survive. */
const textOf = (html) =>
  decode(
    html
      .replace(/<code[^>]*>(.*?)<\/code>/gis, (_, c) => '`' + c.replace(/<[^>]*>/g, '') + '`')
      .replace(/<br\s*\/?>/gi, ' ')
      .replace(/<[^>]+>/g, ' ')
  )
    .replace(/\s+/g, ' ')
    .trim();

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

/* ─────────────────────────────────────────────────────────────────────────────
   1. COMPONENTS — from canvas prose
   Each <section id="x"> is one entry: <h2> name, <p> description + props,
   <h3> variant-group headings. Rendered specimens are dropped.
   ───────────────────────────────────────────────────────────────────────── */
const LAYERS = [
  ['Bayut Profolio Atoms.dc.html', 'atom'],
  ['Bayut Profolio Molecules.dc.html', 'molecule'],
  ['Bayut Profolio Organisms.dc.html', 'organism'],
];

const components = [];
for (const [file, layer] of LAYERS) {
  const html = read(join(CANVAS, file));
  if (!html) { console.warn(`canvas file missing: ${file}`); continue; }

  for (const m of html.matchAll(/<section\s+id="([^"]+)"[^>]*>([\s\S]*?)<\/section>/gi)) {
    const [, id, inner] = m;

    const h2 = inner.match(/<h2[^>]*>([\s\S]*?)<\/h2>/i);
    if (!h2) continue;                                   // nav blocks carry no h2
    const name = textOf(h2[1]);
    if (!name || name.length > 60) continue;

    // paragraphs directly describing the component, before the first specimen card
    const paras = [...inner.matchAll(/<p[^>]*>([\s\S]*?)<\/p>/gi)]
      .map((p) => textOf(p[1]))
      .filter((t) => t.length > 25);

    const variants = [...inner.matchAll(/<h3[^>]*>([\s\S]*?)<\/h3>/gi)]
      .map((h) => textOf(h[1]))
      .filter(Boolean);

    // first backticked path that looks like a source file
    const srcHit = inner.match(/<code[^>]*>([^<]*\/[^<]*\.js)<\/code>/i);

    components.push({
      id, name, layer,
      source: srcHit ? srcHit[1] : '',
      description: paras[0] || '',
      notes: paras.slice(1),
      variants,
    });
  }
}

/* Foundation sections live in the canvas alongside components but are NOT components.
   Filing them under components/ is what made an agent report the font stack as
   undocumented while components/type.md carried it. They go into foundations.md. */
const FOUNDATION_IDS = new Set(['color','type','space','radius','control','iconography','structure']);
const foundationSections = components.filter((c) => FOUNDATION_IDS.has(c.id));
const componentList = components.filter((c) => !FOUNDATION_IDS.has(c.id));

/* ─────────────────────────────────────────────────────────────────────────────
   2. USAGE — which barrel exports are actually imported anywhere
   ───────────────────────────────────────────────────────────────────────── */
const barrel = read(join(REPO, 'src/components/common/index.js'));
const exported = [...barrel.matchAll(/export\s*\{([^}]*)\}/g)]
  .flatMap((m) => m[1].split(','))
  .map((x) => x.replace(/default\s+as\s+/, '').trim())
  .filter((x) => /^[A-Z]/.test(x));

const srcFiles = [];
(function walk(dir) {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) walk(p);
    else if (e.name.endsWith('.js')) srcFiles.push(p);
  }
})(join(REPO, 'src'));

const corpus = srcFiles
  .filter((p) => !p.includes('/components/common/index.js'))
  .map((p) => read(p))
  .join('\n');

const usage = Object.fromEntries(
  exported.map((n) => [n, new RegExp(`\\b${n}\\b`).test(corpus) ? 'used' : 'unreferenced'])
);

/* ─────────────────────────────────────────────────────────────────────────────
   3. ROUTES
   ───────────────────────────────────────────────────────────────────────── */
const routeSrc = ['src/tenant/bayut/routes', 'src/tenant/common/routes']
  .flatMap((d) => {
    const dir = join(REPO, d);
    return existsSync(dir) ? readdirSync(dir).map((f) => read(join(dir, f))) : [];
  })
  .join('\n');

const routes = [...new Set([...routeSrc.matchAll(/path:\s*['"`]([^'"`]+)/g)].map((m) => m[1]))]
  .map((r) => r.replace('${path}', ''))
  .filter((r) => r && r !== '/')
  .sort();

const pageDirs = existsSync(join(REPO, 'src/container/pages'))
  ? readdirSync(join(REPO, 'src/container/pages'), { withFileTypes: true })
      .filter((e) => e.isDirectory()).map((e) => e.name)
  : [];

/* Match a route to the page directory that most likely renders it. */
const SPELLING = {
  'agency-staff': 'agancy-staff', 'packages': 'prop-shop', 'signin': 'authentication',
  'checkout': 'payment', 'event-checkout': 'payment', 'content': 'payment',
  'licenses': 'ad-license', 'invite': 'invite-user', 'preferences': 'user-settings',
  'user-profile': 'user-settings', 'agency-profile': 'user-settings',
  'bank-detail': 'user-settings', 'change-password': 'user-settings',
};
const pageFor = (route) => {
  const seg = route.split('/').filter(Boolean)[0] || '';
  if (SPELLING[seg] && pageDirs.includes(SPELLING[seg])) return SPELLING[seg];
  const norm = (s) => s.replace(/[^a-z]/g, '');
  return pageDirs.find((d) => norm(d) === norm(seg))
      || pageDirs.find((d) => norm(d).startsWith(norm(seg)) && seg.length > 3)
      || '';
};

/* ─────────────────────────────────────────────────────────────────────────────
   4. TENANT FLAGS
   ───────────────────────────────────────────────────────────────────────── */
const flagSrc = read(join(REPO, 'src/tenant/bayut/constants/constants.js'));
const flags = [...flagSrc.matchAll(/^\s{2}([A-Z][A-Z0-9_]{2,}):\s*(.+?),?\s*$/gm)]
  .map(([, k, v]) => ({ key: k, value: v.replace(/,$/, '').slice(0, 60) }));

/* Which files reference each flag — tells a designer what a flag changes. */
const flagSurfaces = Object.fromEntries(
  flags.map((f) => {
    const hits = srcFiles
      .filter((p) => new RegExp(`\\b${f.key}\\b`).test(read(p)))
      .map((p) => p.replace(REPO + '/', ''))
      .filter((p) => !/tenant\/[a-z]+\/constants/.test(p));
    return [f.key, hits.slice(0, 3)];
  })
);

/* ─────────────────────────────────────────────────────────────────────────────
   4b. THE SHELL — menu entries, widths, header parts, read from source
   ───────────────────────────────────────────────────────────────────────── */
const menuFile = read(join(REPO, 'src/tenant/common/menuList/menuList.js'));
const layoutFile = read(join(REPO, 'src/layout/withAdminLayout.js'));

/* Walk menuList in source order. Guards open at `...(cond ?` and close at `: []),`.
   Children live inside `list: [`. Role gating rides on permission/isAgencyPage. */
const menuEntries = [];
{
  let guard = '', inList = false, pending = null;
  const push = () => { if (pending && pending.title) menuEntries.push(pending); pending = null; };
  for (const raw of menuFile.split('\n')) {
    const line = raw.trimEnd();
    const g = line.match(/\.\.\.\(\s*(.+?)\s*$/);
    if (g) guard = g[1].replace(/\?\s*$/, '').replace(/tenantConstants[?.]*\./g, '').trim();
    if (/:\s*\[\]\)/.test(line)) { push(); guard = ''; }
    if (/\blist:\s*\[/.test(line)) { push(); inList = true; }
    else if (inList && /^\s{12}\],\s*$/.test(line)) { push(); inList = false; }

    if (/^\s*\{\s*$/.test(line)) { push(); pending = { title: '', path: '', guard, child: inList, roles: [] }; }
    if (!pending) continue;
    const t = line.match(/title:\s*t\(\s*'([^']+)'/);           if (t) pending.title = t[1];
    const pth = line.match(/path:\s*'([^']+)'/);                 if (pth && !pending.path) pending.path = pth[1];
    const perm = line.match(/permission:\s*PERMISSIONS_TYPE\.(\w+)/); if (perm) pending.roles.push(perm[1].toLowerCase());
    if (/isAgencyPage:\s*true/.test(line)) pending.roles.push('agency only');
    if (/isPremiumUserPage:\s*true/.test(line)) pending.roles.push('premium');
  }
  push();
}

const shellConst = (name) => {
  const m = layoutFile.match(new RegExp(`${name}\\s*=\\s*(\\d+)`));
  return m ? m[1] : '?';
};
const SIDER_W = shellConst('SIDEBAR_EXPANDED_WIDTH');
const SIDER_COLLAPSED_W = shellConst('SIDEBAR_COLLAPSED_WIDTH');

/* ─────────────────────────────────────────────────────────────────────────────
   5. TOKENS
   ───────────────────────────────────────────────────────────────────────── */
const themeSrc = read(join(REPO, 'src/theme/index.js'));
const tokens = [...themeSrc.matchAll(/^\s{2}([a-zA-Z][a-zA-Z0-9]*):\s*'([^']+)'/gm)]
  .map(([, k, v]) => ({ key: k, value: v }));

const lessDirs = ['style.less', 'utils.less', 'antd-customized.less'].map((f) =>
  join(REPO, 'src/static/less', f)
);
const lessAll = lessDirs.map(read).join('\n');
const breakpoints = [...new Set([...lessAll.matchAll(/(?:max|min)-width:\s*(\d+)px/g)].map((m) => +m[1]))]
  .sort((a, b) => a - b);

const fontFamilies = [...new Set(
  [...lessAll.matchAll(/font-family:\s*([^;]+);/g)].map((m) => m[1].replace(/\s+/g, ' ').trim())
)].filter((f) => f.length < 90 && !f.startsWith('@')).slice(0, 6);
const liteFont = (flags.find((f) => f.key === 'FONT_FAMILY_LITE') || {}).value || '';
const radii = [...new Set([...lessAll.matchAll(/border-radius:\s*(\d+px)/g)].map((m) => m[1]))].slice(0, 10);
const zIndexes = [...new Set([...lessAll.matchAll(/z-index:\s*(\d+)/g)].map((m) => +m[1]))].sort((a, b) => a - b);

/* ─────────────────────────────────────────────────────────────────────────────
   EMIT
   ───────────────────────────────────────────────────────────────────────── */
for (const d of ['components']) rmSync(join(REFS, d), { recursive: true, force: true });

const sizes = {};

// components/index.md ────────────────────────────────────────────────────────
sizes['components/index.md'] = write(
  'components/index.md',
  `# Component register

${componentList.length} entries. Load \`components/<id>.md\` for the one you need — never the whole folder,
and never the files in \`canvas/\`.

Design name is canonical. \`source\` is provenance for a developer, not something to fetch.

| Design name | id | Layer | Source | Status |
|---|---|---|---|---|
${componentList
  .map((c) => {
    const st = usage[c.name.replace(/\s+/g, '')] || usage[c.name] || '';
    return `| ${c.name} | \`${c.id}\` | ${c.layer} | ${c.source ? '`' + c.source + '`' : '—'} | ${st || 'n/a'} |`;
  })
  .join('\n')}

## Unreferenced exports

These barrel exports are never imported outside \`src/components/common/\`. Verify before
spending effort on them — "unreferenced" can also mean newly added or used dynamically.

${exported.filter((n) => usage[n] === 'unreferenced').map((n) => `- \`${n}\``).join('\n') || '- none'}
`
);

// components/<id>.md ────────────────────────────────────────────────────────
for (const c of componentList) {
  sizes[`components/${c.id}.md`] = write(
    `components/${c.id}.md`,
    `# ${c.name}

- **layer** ${c.layer}
- **source** ${c.source ? '`' + c.source + '`' : '—'}
- **status** ${usage[c.name.replace(/\s+/g, '')] || 'n/a'}

${c.description}

${c.notes.length ? '\n' + c.notes.map((n) => `> ${n}`).join('\n\n') + '\n' : ''}
${c.variants.length ? `## Variants documented\n\n${c.variants.map((v) => `- ${v}`).join('\n')}` : ''}
`
  );
}


/* ─────────────────────────────────────────────────────────────────────────────
   6. PAGE TEMPLATES — derived per route from its page directory
   ───────────────────────────────────────────────────────────────────────── */

/* Design names come from the sidebar menu — the lingo a PRD will use. */
const menuSrc = read(join(REPO, 'src/tenant/common/menuList/menuList.js'));
const menuLabels = {};
for (const m of menuSrc.matchAll(/key:\s*['"]([^'"]+)['"][\s\S]{0,400}?t\(\s*['"]([^'"]+)['"]/g)) {
  menuLabels[m[1]] = m[2];
}
for (const m of menuSrc.matchAll(/t\(\s*['"]([^'"]+)['"][\s\S]{0,200}?key:\s*['"]([^'"]+)['"]/g)) {
  if (!menuLabels[m[2]]) menuLabels[m[2]] = m[1];
}

const filesIn = (dir) => {
  const out = [];
  if (!existsSync(dir)) return out;
  (function walk(d) {
    for (const e of readdirSync(d, { withFileTypes: true })) {
      const q = join(d, e.name);
      if (e.isDirectory()) walk(q);
      else if (e.name.endsWith('.js')) out.push(q);
    }
  })(dir);
  return out;
};

const componentByName = new Map(componentList.map((c) => [c.name.toLowerCase(), c]));
const ALIAS = {
  EmptyState: 'empty', JSONForm: 'form', Spinner: 'feedback', Skeleton: 'feedback',
  TextInput: 'input', Select: 'select', Cards: 'card', Card: 'card', DataTable: 'table',
  Drawer: 'drawer', Modal: 'modal', Dropdown: 'dropdown', Tabs: 'tabs', Tag: 'tag',
  Button: 'button', Icon: 'icon', Avatar: 'avatar', Alert: 'alert', Switch: 'switch',
  Statistic: 'statistic', Banner: 'banner', Filters: 'filters', FilterTag: 'filterchip',
  Label: 'label', Divider: 'misc', Pagination: 'pagination', Navbar: 'navitem',
  Segmented: 'segmented', Checkbox: 'checkbox', RadioButtons: 'radio', Upload: 'upload',
  'image-uploads': 'upload', 'phone-input': 'phone', 'header-search': 'search',
  'listing-card': 'listingcard', 'listing-health': 'health', widgets: 'dashboard',
  'notification-center': 'notification', table: 'table', charts: 'dashboard',
  'product-tag': 'producttag', 'json-form': 'form', dataTable: 'table', EmptyStates: 'empty',
};
const resolveComp = (n) => {
  const id = ALIAS[n] || ALIAS[n.replace(/s$/, '')];
  if (id) return componentList.find((c) => c.id === id);
  return componentByName.get(n.toLowerCase())
      || componentList.find((c) => c.id === slug(n))
      || componentList.find((c) => slug(c.name) === slug(n));
};
const TITLECASE = (s) => s.replace(/[-/]/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase()).trim();

let templatesWritten = 0;
for (const route of routes) {
  const dir = pageFor(route);
  if (!dir) continue;                                   // no page dir → no template to derive
  const pageFiles = filesIn(join(REPO, 'src/container/pages', dir));
  let src = pageFiles.map(read).join('\n');
  if (!src) continue;

  // Several screens are thin pages whose logic lives in feature dirs they never import
  // directly (post-listing drives everything through JSONForm, for instance). Curated.
  const EXTRA = {
    'post-listing': ['components/post-listing', 'components/post-listing-ksa',
                     'helpers/post-listing', 'tenant/common/components/post-listing'],
    'post-ad':      ['components/post-listing', 'helpers/post-listing'],
    'checkout':     ['components/checkout', 'components/prop-shop'],
    'prop-shop':    ['components/prop-shop', 'components/checkout'],
    'listings':     ['components/listing-card', 'components/listing-container',
                     'components/listing-drawer', 'components/table'],
    'dashboard':    ['components/widgets', 'components/charts'],
    'credits-usage':['components/credits-usage', 'components/credits-info'],
    'quota-credits':['components/credits-usage', 'components/set-credit-limit'],
    'agancy-staff': ['components/agency-staff-header', 'components/invite-user',
                     'components/delete-agency-user'],
    'user-settings':['components/add-license', 'components/license-card',
                     'components/nafath-verification-modal'],
    'ad-license':   ['components/add-license', 'components/license-card'],
    'lms':          ['components/leads-management', 'components/lead-nudges'],
  };
  for (const extra of EXTRA[dir] || [])
    src += '\n' + filesIn(join(REPO, 'src', extra)).map(read).join('\n');

  // follow one level into the feature components this page pulls in — that is where
  // the KSA logic (flags, role branching) actually lives for most screens
  const followed = new Set(
    [...src.matchAll(/from\s*'[^']*\/components\/([a-zA-Z-]+)'/g)].map((m) => m[1])
  );
  for (const f of followed) {
    if (f === 'common' || f === 'svg') continue;
    src += '\n' + filesIn(join(REPO, 'src/components', f)).map(read).join('\n');
  }

  const seg = route.split('/').filter(Boolean)[0] || '';
  const designName = menuLabels[seg] || menuLabels[dir] || TITLECASE(seg);

  // components: named imports from the common barrel, plus direct component paths
  const named = new Set();
  for (const m of src.matchAll(/import\s*\{([^}]+)\}\s*from\s*'[^']*components\/common'/g))
    m[1].split(',').forEach((n) => { const t = n.trim(); if (/^[A-Z]/.test(t)) named.add(t); });
  const direct = new Set(
    [...src.matchAll(/from\s*'[^']*components\/(?:common\/)?([a-zA-Z-]+)(?:\/[^']*)?'/g)]
      .map((m) => m[1]).filter((n) => n !== 'common' && n !== 'svg')
  );

  // map to documented entries where we can
  const docd = [...new Set([...named, ...direct])]
    .map((n) => {
      const hit = resolveComp(n);
      return hit ? `\`components/${hit.id}.md\` (${hit.name})` : null;
    })
    .filter(Boolean);
  const docdUniq = [...new Set(docd)];
  const undoc = [...new Set([...named, ...direct].filter((n) => !resolveComp(n)))];

  // Flags that gate the ROUTE itself live in menuList/appRoutes, not in the page.
  const routeGuard = new Set();
  const guardSrc = menuSrc + '\n' + routeSrc;
  for (const m of guardSrc.matchAll(/tenantConstants[?.]*\.([A-Z][A-Z0-9_]+)([\s\S]{0,600}?)(?=tenantConstants[?.]*\.[A-Z]|$)/g)) {
    if (m[2].includes(`'${seg}'`) || m[2].includes(`"${seg}"`) || m[2].includes(`/${seg}`))
      routeGuard.add(m[1]);
  }

  const usedFlags = [...new Set(
    [...src.matchAll(/tenantConstants[?.]*\.([A-Z][A-Z0-9_]+)/g)].map((m) => m[1])
  )].filter((f) => flags.some((x) => x.key === f));
  const gateFlags = [...routeGuard].filter((f) => flags.some((x) => x.key === f) && !usedFlags.includes(f));

  const roleAware = /is_agency|isAgency|user_type|PERMISSIONS_TYPE/.test(src);
  const states = [
    /isLoading|loading|Skeleton|Spinner/.test(src) && 'loading',
    /EmptyState|no-data|noData/.test(src) && 'empty',
    /error|Error/.test(src) && 'error',
    usedFlags.length && 'flag-off',
    roleAware && 'no-permission',
  ].filter(Boolean);

  /* Layout skeleton — the JSX nesting IS the layout. Keep structural tags and the
     props that carry layout intent; drop handlers, data and styling noise. */
  const LAYOUT_PROPS = /\b(template|gap|vertical|justify|align|span|cols?|direction|wrap|width|height|type|shape|size)=(?:"[^"]*"|\{[^}]{0,40}\})/g;
  const skeletonOf = (code) => {
    const out = [];
    for (const line of code.split('\n')) {
      const m = line.match(/^(\s*)<\/?([A-Z][A-Za-z0-9]*)([^>]*)>?/);
      if (!m) continue;
      const [, indent, tag, rest] = m;
      if (/^(Trans|Fragment|React)$/.test(tag)) continue;
      const closing = /^\s*<\//.test(line);
      const props = closing ? [] : (rest.match(LAYOUT_PROPS) || []).slice(0, 3);
      const depth = Math.min(Math.floor(indent.length / 2), 8);
      out.push(`${'  '.repeat(depth)}${closing ? '/' : ''}${tag}${props.length ? ' ' + props.join(' ') : ''}`);
    }
    // collapse consecutive duplicates (repeated list items render identically)
    return out.filter((l, i) => l !== out[i - 1]).slice(0, 70).join('\n');
  };
  const mainFile = pageFiles.find((f) => /\/(index|[a-z-]+)\.js$/.test(f) && !/style|util|helper/i.test(f))
                || pageFiles[0];
  const skeleton = skeletonOf(read(mainFile));

  const shotFile = `screens/${slug(route)}.png`;
  const hasShot = existsSync(join(REFS, shotFile));

  const body = `# ${designName}

> **Derived, not designed.** Fields below were read out of the page directory. Purpose, layout
> intent and the artboard are still to be written — that is the designer's work, and this
> header is the proposal to get approved first.

\`\`\`
shell     default
route     ${route}
source    src/container/pages/${dir}
purpose   TODO — one sentence, user-side
roles     ${roleAware ? 'role-aware — agency owner / agency staff / individual seller differ; confirm which' : 'no role branching found in this directory'}
flags     ${[...gateFlags.map((f) => f + ' (gates the route)'), ...usedFlags].join(' · ') || 'none referenced directly'}
states    ${states.length ? states.join(' · ') : 'none detected — confirm with the designer'}
lang      en pending · ar pending
ga4       — product supplies in the PRD
shot      ${hasShot ? '`references/' + shotFile + '` — OPEN IT BEFORE DESIGNING' : 'not captured — run scripts/capture.mjs'}
board     \`references/pages/${slug(route)}.html\` — open in a browser to see this screen
\`\`\`
${hasShot ? `
## Reference screenshot

\`references/${shotFile}\` — the live screen. **Open it before you design.** The skeleton gives
structure, the component specs give values, this gives the truth. If your output disagrees
with it, your output is wrong.
` : `
## Reference screenshot

**Not captured yet.** Run \`node scripts/capture.mjs --login\` once, then
\`node scripts/capture.mjs\`, then re-run the build. Until then you have structure and values
but no visual reference — say so rather than implying your output matches the live screen.
`}

## Composition

Documented components this page already imports:

${docdUniq.length ? docdUniq.map((d) => `- ${d}`).join('\n') : '- none resolved automatically — check `components/index.md`'}

${undoc.length ? `Imported but **not in the component register** — undocumented surface:\n\n${undoc.slice(0, 14).map((n) => `- \`${n}\``).join('\n')}\n` : ''}
## Layout skeleton

Nesting and layout props read out of \`${mainFile.replace(REPO + '/', '')}\`. This is the
shipped structure — **match it rather than inventing a new one**, unless the PRD changes it.

\`\`\`
${skeleton || '(no JSX structure resolved — check the source directly)'}
\`\`\`

## Before designing

1. Fill in \`purpose\` and confirm \`roles\`.
2. Check every flag above in \`flags.md\` — a false flag removes the surface.
3. Start from \`pages/_shell.md\` default unless the PRD says otherwise.
4. Get this header approved, then design.
`;
  sizes[`pages/${slug(route)}.md`] = write(`pages/${slug(route)}.md`, body);
  templatesWritten++;
}
console.log(`templates        ${templatesWritten}`);

// pages/index.md ────────────────────────────────────────────────────────────
sizes['pages/index.md'] = write(
  'pages/index.md',
  `# Screen map

${routes.length} routes. Every screen inherits \`pages/_shell.md\` unless its own file says otherwise.

A PRD names a screen in design language. Match on that; cite the repo path.
No match → ask the designer whether to remake it or receive it. Never improvise.

**Templates marked \`not written\` do not exist yet.** Do not try to load them. For those
screens you have the shell, the route, the page source and the component register — say
that plainly, propose a composition from \`components/index.md\`, and get it approved
before designing. Never pretend a template was read.

| Route | Page source | Template |
|---|---|---|
${routes
  .map((r) => {
    const p = pageFor(r);
    const tpl = `pages/${slug(r)}.md`;
    const exists = existsSync(join(REFS, tpl));
    const t = exists ? `\`${tpl}\`` : '**not written**';
    return `| \`${r}\` | ${p ? '`src/container/pages/' + p + '`' : '—'} | ${t} |`;
  })
  .join('\n')}
`
);

// flags.md ──────────────────────────────────────────────────────────────────
sizes['flags.md'] = write(
  'flags.md',
  `# KSA tenant flags

${flags.length} constants from \`src/tenant/bayut/constants/constants.js\`. These define what
Profolio KSA *is*. A flag that is false removes or changes a surface — check before designing it.

| Flag | Value | Referenced in |
|---|---|---|
${flags
  .map((f) => `| \`${f.key}\` | \`${f.value}\` | ${(flagSurfaces[f.key] || []).map((s) => '`' + s + '`').join(' ') || '—'} |`)
  .join('\n')}
`
);

// foundations.md ────────────────────────────────────────────────────────────
sizes['foundations.md'] = write(
  'foundations.md',
  `# Foundations

**This file is complete.** Colour, typography, spacing, radius, elevation and iconography are
all here. Do not conclude something is undocumented without reading to the bottom.

Cite token names, not hex values. The cascade resolves in three layers, last wins:
\`src/theme/index.js\` → styled-components → \`src/static/less/style.less\`.

## Typography

Font stacks found in \`src/static/less/style.less\`:

${fontFamilies.map((f) => `- \`${f}\``).join('\n')}

Lite / member-area surfaces swap family via \`FONT_FAMILY_LITE\` = \`${liteFont}\`.

${foundationSections.filter((f) => f.id === 'type').map((f) => f.description + (f.variants.length ? '\n\n' + f.variants.map((v) => `- ${v}`).join('\n') : '')).join('\n\n')}

## Colour tokens

| Token | Value |
|---|---|
${tokens.map((t) => `| \`${t.key}\` | \`${t.value}\` |`).join('\n')}

${foundationSections
  .filter((f) => f.id !== 'type')
  .map((f) => `## ${f.name}\n\n${f.description}${f.notes.length ? '\n\n' + f.notes.map((n) => `> ${n}`).join('\n\n') : ''}${f.variants.length ? '\n\n' + f.variants.map((v) => `- ${v}`).join('\n') : ''}`)
  .join('\n\n')}

## Radius in use

${radii.join(' · ') || '—'}

## Breakpoints in use

${breakpoints.join(' · ')} px

Inconsistent by inheritance — 991/992, 767/768, 575/576 and 479/480 all appear. Until a
canonical scale is agreed, match the value already used by the surface you are changing.

## z-index in use

${zIndexes.join(' · ')}

No layer model. The \`2147483647\` is real and is in the codebase.
`
);

// pages/_shell.md — GENERATED; supersedes the hand-written version ──────────
const navRows = menuEntries.map((e) =>
  `| ${e.child ? '&nbsp;&nbsp;↳ ' : ''}**${e.title}** | \`${e.path || '— (parent)'}\` | ${e.guard ? '`' + e.guard + '`' : 'always'} | ${e.roles.length ? e.roles.join(', ') : 'all'} |`
).join('\n');

const navHtml = menuEntries.filter((e) => !e.child)
  .map((e, i) => {
    const kids = e.path ? '' : menuEntries.filter((k) => k.child)
      .map((k) => `\n      <a href="${k.path}">${k.title}</a>`).join('');
    return e.path
      ? `    <a href="${e.path}"${i === 0 ? ' class="on"' : ''}>${e.title}</a>`
      : `    <div class="grp"><span>${e.title}</span>${kids}\n    </div>`;
  }).join('\n');

sizes['pages/_shell.md'] = write(
  'pages/_shell.md',
  `# The Profolio shell

**Every Profolio KSA screen starts here.** There is no blank canvas. A screen that does not
exist yet still has the header, side navigation and footer — so the worst case a designer
receives is correct chrome around an empty content area, never an improvised layout.

Source: \`src/layout/withAdminLayout.js\` · \`src/tenant/common/menuList/menuList.js\`

## Measurements — use these, do not estimate

| Part | Value | Source |
|---|---|---|
| Sider width, expanded | **${SIDER_W}px** | \`SIDEBAR_EXPANDED_WIDTH\` |
| Sider width, collapsed | **${SIDER_COLLAPSED_W}px** | \`SIDEBAR_COLLAPSED_WIDTH\` |
| Header height | **74px** | layout |
| Content ground | \`#F6F7FB\` | layout |
| Page header padding | \`24px 32px\` (\`26px 15px\` ≤768px, \`16px 20px\` ≤576px) | style.less |
| Footer | \`#fafafa\` · \`24px 15px\` | layout |
| Mobile sider drawer | 280px at \`top: 75px\`, 0.35s ease-in | layout |

## The sidebar — these exact ${menuEntries.length} entries, these exact labels

Never invent, rename, reorder or omit one. "TruLeads" is not "Leads"; "Credits & Packages" is
not "Packages"; there is no top-level "Licenses" entry.

| Label | Path | Shown when | Roles |
|---|---|---|---|
${navRows}

## Header parts, in order

1. Logo — Bayut + KSA lockup
2. Header search — **hidden on KSA**, \`SHOW_SEARCH_HEADER: false\`
3. Platform segmented control — multi-platform users only
4. Credits summary
5. Notification bell with unread badge
6. **Classified pill** — a link out to the classified site, min-width 148.71px, 1px \`#f0f0f0\`
   border, radius 6px, 36px tall. It is a bordered link, **not a solid primary button**, and
   it is not "Post a Listing".
7. Account dropdown — avatar plus name

## Starting markup

Copy this. It is the shell at the measurements above, with the real nav. Replace only the
content area.

\`\`\`html
<div class="pf">
  <header class="pf-header">
    <div class="pf-logo">bayut <span>KSA</span></div>
    <div class="pf-spacer"></div>
    <div class="pf-credits"><em>Credits</em><b>1,280</b></div>
    <button class="pf-bell" aria-label="Notifications">7</button>
    <a class="pf-classified" href="#">Go to Bayut.sa</a>
    <div class="pf-account"><span class="av">SA</span> Saad Al-Harbi</div>
  </header>
  <nav class="pf-sider">
${navHtml}
  </nav>
  <main class="pf-content"><!-- the screen goes here --></main>
  <footer class="pf-footer">
    <small>© 2026 Bayut KSA</small>
    <span class="rega">Licensed by <b>REGA</b> · <a href="#">Report to REGA</a></span>
  </footer>
</div>

<style>
.pf{display:grid;grid-template-columns:${SIDER_W}px 1fr;background:#F6F7FB;
    font-family:Lato,'Droid Arabic Kufi',sans-serif;font-size:14px;line-height:1.571;color:#222}
.pf-header{grid-column:1/-1;height:74px;background:#fff;border-bottom:1px solid #F1F2F6;
    display:flex;align-items:center;gap:18px;padding:0 24px}
.pf-logo{width:${SIDER_W - 24}px;flex:none;font-weight:900;color:#006169;font-size:19px}
.pf-logo span{font-weight:400;font-size:12px;color:#9D9D9D;text-transform:uppercase}
.pf-spacer{flex:1}
.pf-credits{display:flex;flex-direction:column;padding-inline-end:18px;border-right:1px solid #f0f0f0}
.pf-credits em{font-style:normal;font-size:10.5px;color:#9D9D9D;text-transform:uppercase}
.pf-credits b{font-size:14px;color:#222}
.pf-bell{background:none;border:0;color:#5A5F7D;cursor:pointer}
.pf-classified{min-width:148.71px;height:36px;border:1px solid #f0f0f0;border-radius:6px;
    display:grid;place-items:center;padding:0 16px;color:#767676;text-decoration:none;font-size:13px}
.pf-account{display:flex;align-items:center;gap:9px;font-size:13px;color:#4f4f4f}
.pf-account .av{width:36px;height:36px;border-radius:50%;background:#E1F2F0;color:#006169;
    display:grid;place-items:center;font-weight:700;font-size:13px}
.pf-sider{background:#fff;border-right:1px solid #F1F2F6;padding:30px 0 0}
.pf-sider a{display:block;padding:8px 16px;margin:0 15px 8px;border-radius:4px;
    font-weight:500;color:#222;text-decoration:none}
.pf-sider a:hover{background:#F8F9FB;color:#006169}
.pf-sider a.on{background:#F7FCFC;color:#006169;font-weight:600}
.pf-sider .grp>span{display:block;padding:8px 16px;margin:0 15px;font-weight:500;color:#222}
.pf-sider .grp a{font-weight:400;padding-block:7px;margin-inline-start:31px}
.pf-content{padding:24px 32px;display:grid;grid-template-rows:auto 1fr;gap:16px}
.pf-footer{grid-column:1/-1;background:#fafafa;padding:24px 15px;border-top:1px solid #F1F2F6;
    display:flex;justify-content:space-between;gap:16px;flex-wrap:wrap;font-size:11.5px;color:#707070}
.pf-footer b{color:#006169}
@media (max-width:992px){.pf{grid-template-columns:1fr}.pf-sider{display:none}}
</style>
\`\`\`

## Variants

\`withAdminLayout.js\` branches four ways. Name which one you are designing.

| Variant | Condition | What changes |
|---|---|---|
| \`isMobile\` | ≤992px | Sider → 280px drawer at \`top:75px\`. \`lite-header-dropdown\` replaces the account menu; \`lite-sidebar-drawer\` replaces the sider. Cards lose their border; selects shrink to 40px. |
| \`isMemberArea\` | \`HAS_MEMBER_AREA: true\` on KSA | Reduced chrome. **This is the lite surface — v2, not specified.** Stop and say so. |
| \`topMenu\` | layout preference | Horizontal nav replaces the sider. |
| \`isWebView\` | embedded in the app | Chrome suppressed entirely. |

## Page template header

Every \`pages/<route>.md\` opens with these fields. Filling it in **is** the proposal.

\`\`\`
shell     default | isMobile | isMemberArea | topMenu | isWebView
route     /the-route
source    src/container/pages/<dir>
purpose   one sentence, user-side
roles     agency owner · agency staff · individual seller — and what differs
flags     tenant constants that change or remove it
uses      documented components it composes
states    loading · empty · error · flag-off · no-permission
lang      en <draft|approved> · ar <pending|passed>
ga4       event names, when product supplies them
\`\`\`
`
);

/* ─────────────────────────────────────────────────────────────────────────────
   7. COPY — the real product strings, grouped by the area that uses them
   The skill shipped none of these, which is why an agent invented every label.
   ───────────────────────────────────────────────────────────────────────── */
const enCopy = (() => { try { return JSON.parse(read(join(REPO, 'src/locales/en/translation.json'))); } catch { return {}; } })();
const arCopy = (() => { try { return JSON.parse(read(join(REPO, 'src/locales/ar/translation.json'))); } catch { return {}; } })();

/* Which area does a source file belong to? */
const areaOf = (path) => {
  const rel = path.replace(REPO + '/src/', '');
  let m = rel.match(/^container\/pages\/([^/]+)/);      if (m) return `page-${m[1]}`;
  m = rel.match(/^components\/common\/([^/]+)/);         if (m) return `common-${m[1]}`;
  m = rel.match(/^components\/([^/.]+)/);                if (m) return m[1];
  m = rel.match(/^tenant\/[^/]+\/components\/([^/]+)/);  if (m) return `tenant-${m[1]}`;
  if (rel.startsWith('layout')) return 'shell';
  return '';
};

/* t('…') and t("…") calls, per area, in first-seen order. */
const copyByArea = new Map();
for (const f of srcFiles) {
  const area = areaOf(f);
  if (!area) continue;
  const src = read(f);
  const keys = [...src.matchAll(/\bt\(\s*['"]([^'"]{2,120})['"]/g)].map((m) => m[1]);
  if (!keys.length) continue;
  if (!copyByArea.has(area)) copyByArea.set(area, new Set());
  const bucket = copyByArea.get(area);
  for (const k of keys) if (enCopy[k] !== undefined) bucket.add(k);
}

const copyAreas = [...copyByArea.entries()]
  .map(([area, set]) => ({ area, keys: [...set].sort() }))
  .filter((a) => a.keys.length)
  .sort((a, b) => b.keys.length - a.keys.length);

for (const { area, keys } of copyAreas) {
  sizes[`copy/${area}.md`] = write(
    `copy/${area}.md`,
    `# Copy — ${area}

${keys.length} strings shipped in this area. **Use these exact words.** If a label you need is
not here, say so rather than writing one — invented copy is how "Post a Listing" ended up on
the classified pill.

| English | Arabic |
|---|---|
${keys.map((k) => `| ${enCopy[k].replace(/\|/g, '\\|')} | ${(arCopy[k] || '—').replace(/\|/g, '\\|')} |`).join('\n')}
`
  );
}

sizes['copy/index.md'] = write(
  'copy/index.md',
  `# Product copy

Every user-facing string in Profolio, grouped by the area that renders it, English beside
Arabic. Load the one area you are designing — never the whole folder.

**Rule: never invent a label.** If the string is not in the relevant file, say which file you
checked and ask. A plausible-sounding invented label is the failure mode this layer exists to
stop.

${enCopy && Object.keys(enCopy).length} strings total in \`src/locales/en/translation.json\`.

| Area | Strings | File |
|---|---|---|
${copyAreas.map((a) => `| ${a.area} | ${a.keys.length} | \`copy/${a.area}.md\` |`).join('\n')}
`
);
console.log(`copy areas       ${copyAreas.length}`);

/* ─────────────────────────────────────────────────────────────────────────────
   8. FEATURE COMPONENTS — one entry per real component dir, from its own source
   The canvas documented 57 generic components. The product has far more, and the
   ones a PRD actually names (TruPoints, Bayut Match, credits quota) were blanks.
   ───────────────────────────────────────────────────────────────────────── */
const covered = new Set(componentList.map((c) => slug(c.name)));
for (const c of componentList) covered.add(c.id);

const compDirs = [];
for (const base of ['components', 'components/common']) {
  const dir = join(REPO, 'src', base);
  if (!existsSync(dir)) continue;
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    if (e.isDirectory()) compDirs.push({ name: e.name, base, dir: join(dir, e.name) });
  }
}

/* Pull real declarations out of styled-components template literals. */
const cssOf = (src) => {
  const decls = new Set();
  for (const m of src.matchAll(/styled\.[a-zA-Z]+`([\s\S]*?)`|styled\([^)]+\)`([\s\S]*?)`|css`([\s\S]*?)`/g)) {
    const body = m[1] || m[2] || m[3] || '';
    for (const d of body.matchAll(/([a-z-]{3,})\s*:\s*([^;{}\n]{1,60});/g)) {
      const [, prop, val] = d;
      if (/\$\{/.test(val) && !/tenantTheme|theme\./.test(val)) continue;   // skip opaque interpolation
      decls.add(`${prop}: ${val.trim().replace(/\$\{[^}]*?([a-zA-Z0-9_'\[\]-]+)\}/g, '$1')}`);
    }
  }
  return [...decls];
};

let featureCount = 0;
for (const { name, base, dir } of compDirs) {
  const id = slug(name);
  if (covered.has(id)) continue;                         // canvas already documents it

  const files = [];
  (function walk(d) {
    for (const e of readdirSync(d, { withFileTypes: true })) {
      const q = join(d, e.name);
      if (e.isDirectory()) walk(q); else if (e.name.endsWith('.js')) files.push(q);
    }
  })(dir);
  if (!files.length) continue;

  const all = files.map(read).join('\n');
  const css = cssOf(all);
  const props = [...new Set(
    [...all.matchAll(/(?:const|function)\s+[A-Z]\w*\s*=?\s*\(?\s*\{([^}]{5,400})\}/g)]
      .flatMap((m) => m[1].split(','))
      .map((x) => x.split(/[:=]/)[0].trim())
      .filter((x) => /^[a-z]\w{1,28}$/.test(x))
  )].slice(0, 18);
  const strings = [...new Set([...all.matchAll(/\bt\(\s*['"]([^'"]{2,60})['"]/g)].map((m) => m[1]))].slice(0, 10);
  const usesFlags = [...new Set([...all.matchAll(/tenantConstants[?.]*\.([A-Z][A-Z0-9_]+)/g)].map((m) => m[1]))];


  sizes[`components/${id}.md`] = write(
    `components/${id}.md`,
    `# ${name}

- **layer** feature
- **source** \`src/${base}/${name}\`
- **derived from** the component's own source, not the design canvas

${props.length ? `## Props\n\n${props.map((x) => `\`${x}\``).join(' · ')}\n` : ''}
${!css.length && !strings.length ? `> No styling or copy of its own — it composes other components. Check its source for what it wraps.
` : ''}
${css.length ? `## Measured CSS\n\nRead out of this component's styled rules — these are the shipped values.\n\n\`\`\`css\n${css.slice(0, 28).join(';\n')};\n\`\`\`\n` : ''}
${strings.length ? `## Copy it renders\n\n${strings.map((x) => `- ${x}`).join('\n')}\n\nFull list with Arabic: \`copy/${areaOf(files[0]) || id}.md\`\n` : ''}
${usesFlags.length ? `## Flags\n\n${usesFlags.map((f) => `\`${f}\``).join(' · ')}\n` : ''}`
  );
  featureCount++;
}
console.log(`feature comps    ${featureCount}`);

/* ─────────────────────────────────────────────────────────────────────────────
   9. PAGE ARTBOARDS — a viewable .html beside every page's .md
   The markdown says what a screen is; this shows it. Shell chrome is real,
   the content area is blocked out from the layout skeleton so a designer
   starts from the right structure rather than an empty box.
   ───────────────────────────────────────────────────────────────────────── */
const shellMd = read(join(REFS, 'pages/_shell.md'));
const shellHtml = (shellMd.match(/```html\n([\s\S]*?)```/) || [, ''])[1];

/* Turn a skeleton line into a blocked-out region. */
const blockFor = (tag, props) => {
  const t = tag.toLowerCase();
  if (/card|widget|container|section|quota|breakdown|status/.test(t)) return 'card';
  if (/table|list/.test(t)) return 'table';
  if (/chart|graph|traffic/.test(t)) return 'chart';
  if (/stat|points|metric|credit/.test(t)) return 'stat';
  if (/button|btn|cta/.test(t)) return 'btn';
  if (/select|dropdown|filter/.test(t)) return 'field';
  if (/group|flex|row|col|main/.test(t)) return props.includes('template') ? 'grid' : 'flow';
  return 'blk';
};

let boards = 0;
for (const route of routes) {
  const dir = pageFor(route);
  if (!dir || !shellHtml) continue;
  const mdPath = join(REFS, `pages/${slug(route)}.md`);
  if (!existsSync(mdPath)) continue;

  const pageMd = read(mdPath);
  const skel = (pageMd.match(/## Layout skeleton[\s\S]*?```\n([\s\S]*?)```/) || [, ''])[1];
  const title = (pageMd.match(/^#\s+(.+)$/m) || [, route])[1];
  const flags = (pageMd.match(/^flags\s+(.+)$/m) || [, '—'])[1];
  const roles = (pageMd.match(/^roles\s+(.+)$/m) || [, '—'])[1];

  /* Build content blocks from the skeleton's top-level structure. */
  const seen = new Set();
  const regions = skel.split('\n')
    .map((l) => l.match(/^(\s*)([A-Z][A-Za-z0-9]*)(.*)$/))
    .filter(Boolean)
    .filter((m) => m[1].length <= 14)
    /* wrappers and loading plumbing are not content — skip them */
    .filter((m) => !/^(Flex|Main|Spinner|Skeleton|LoaderWrapper|Row|Col|Trans|Fragment|Group)$/.test(m[2])
                || /template=/.test(m[3] || ''))
    .map((m) => ({ depth: m[1].length, tag: m[2], props: m[3] || '' }))
    .filter((r) => { if (seen.has(r.tag)) return false; seen.add(r.tag); return true; })
    .slice(0, 9);

  const content = regions.length ? regions.map((r) => {
    const kind = blockFor(r.tag, r.props);
    const gridProp = (r.props.match(/template="([^"]+)"/) || [, ''])[1];
    return `      <div class="ab ab-${kind}"${gridProp ? ` style="--tpl:${gridProp}"` : ''}>
        <span class="ab-tag">${r.tag}</span>${gridProp ? `<span class="ab-note">${gridProp}</span>` : ''}
      </div>`;
  }).join('\n') : '      <div class="ab ab-blk"><span class="ab-tag">content</span></div>';

  const board = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${title} — Profolio KSA artboard</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700;900&display=swap">
<style>
body{margin:0;background:#e9edee;font-family:Lato,Arial,sans-serif}
.meta{max-width:1440px;margin:0 auto;padding:18px 20px 0;font:12px ui-monospace,monospace;color:#5c716e;line-height:1.9}
.meta b{color:#006169;font-weight:600}
.frame{max-width:1440px;margin:12px auto 40px;border:1px solid #ccd8d5;background:#fff;overflow:hidden}
.ab{border:1.5px dashed #b9c9c6;border-radius:8px;background:
 repeating-linear-gradient(-45deg,#fbfcfc 0 10px,#f4f7f7 10px 20px);
 min-height:96px;display:flex;align-items:center;justify-content:center;gap:10px;flex-wrap:wrap;padding:16px}
.ab-tag{font:600 11px ui-monospace,monospace;letter-spacing:.09em;text-transform:uppercase;color:#6f817d}
.ab-note{font:11px ui-monospace,monospace;color:#9aa8a5}
.ab-card{min-height:150px}.ab-table{min-height:230px}.ab-chart{min-height:210px}
.ab-stat{min-height:86px}.ab-btn{min-height:48px;max-width:190px}.ab-field{min-height:44px;max-width:230px}
.ab-grid{min-height:150px}
</style></head><body>
<div class="meta">
  <b>${title}</b> · ${route}<br>
  roles ${roles}<br>
  flags ${flags}<br>
  <i>Artboard — real shell chrome, content blocked out from the layout skeleton. Replace the blocks.</i>
</div>
<div class="frame">
${shellHtml.replace('<main class="pf-content"><!-- the screen goes here --></main>', `<main class="pf-content">
      <div style="display:flex;align-items:center;justify-content:space-between;gap:16px">
        <h3 style="margin:0;font-size:20px;font-weight:700;color:#222">${title}</h3>
      </div>
${content}
    </main>`)}
</div>
</body></html>`;

  writeFileSync(join(REFS, `pages/${slug(route)}.html`), board);
  boards++;
}
console.log(`artboards        ${boards}`);

/* report ------------------------------------------------------------------- */
const total = Object.values(sizes).reduce((a, b) => a + b, 0);
console.log(`source            profolio-reactjs@${SOURCE_SHA}`);
console.log(`components        ${components.length}`);
console.log(`routes            ${routes.length}`);
console.log(`flags             ${flags.length}`);
console.log(`tokens            ${tokens.length}`);
console.log(`unreferenced      ${exported.filter((n) => usage[n] === 'unreferenced').length}`);
console.log(`files written     ${Object.keys(sizes).length}`);
console.log(`generated bytes   ${total} (~${Math.round(total / 4)} tokens if all loaded at once)`);
const perComp = components.length
  ? Math.round(components.reduce((a, c) => a + (sizes[`components/${c.id}.md`] || 0), 0) / components.length)
  : 0;
console.log(`avg component     ${perComp} bytes (~${Math.round(perComp / 4)} tokens)`);
