#!/usr/bin/env node
/**
 * Extracts the four layers the generator never read.
 *
 * `build.mjs` pulls components, routes, flags, tokens, copy and artboards out
 * of the codebase. It does not read these, and that is precisely why the design
 * system had sixteen open questions that were never open at all:
 *
 *   tenant/<t>/data/        the colour maps — classification, packages, platforms
 *   static/less/utils.less  the real spacing, size and weight scales
 *   table/ + listingUtilities.js  columns, dispositions, actions, enable rules
 *   hooks/useAppInit.js     which fonts the browser is actually given
 *
 * A sibling of build.mjs rather than four more sections inside it: that file is
 * already a thousand lines and nine sections, and these read different kinds of
 * source in different ways.
 *
 *   node scripts/extract-layers.mjs --repo ../profolio-reactjs-copy --tenant bayut
 *
 * Writes references/data/*.md. Regenerate whenever the product moves.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execSync } from 'node:child_process';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const arg = (n, d) => { const i = process.argv.indexOf(n); return i > -1 ? process.argv[i + 1] : d; };
const REPO = join(ROOT, arg('--repo', '../profolio-reactjs-copy'));
const TENANT = arg('--tenant', 'bayut');
const OUT = join(ROOT, 'references', 'data');

const read = (p) => (existsSync(join(REPO, p)) ? readFileSync(join(REPO, p), 'utf8') : '');
const rel = (p) => p.replace(REPO + '/', '');
let commit = 'unknown';
try { commit = execSync('git rev-parse --short HEAD', { cwd: REPO }).toString().trim(); } catch {}

const banner = (title, sources) =>
`<!-- GENERATED by scripts/extract-layers.mjs from profolio-reactjs @ ${commit} — do not edit. -->

# ${title}

Read from:
${sources.map((s) => `- \`${s}\``).join('\n')}
`;

const written = [];
const write = (name, body) => {
  mkdirSync(OUT, { recursive: true });
  writeFileSync(join(OUT, name), body.replace(/\n{3,}/g, '\n\n').trimEnd() + '\n');
  written.push([name, Buffer.byteLength(body)]);
};

/* ═══ 1 · colour maps ══════════════════════════════════════════════════════
   These decide what colour a ring, a badge or a tag is, and none of them is a
   theme token. Every one was a "cannot tell" until someone opened the file. */
{
  const statics = read(`src/tenant/common/data/staticLists.js`);
  const packages = read(`src/tenant/${TENANT}/data/packages.js`);
  const tenantStatics = read(`src/tenant/${TENANT}/data/staticLists.js`);

  const classification = [...statics.matchAll(/case\s+'(\w+)':\s*\n?\s*return\s+tenantTheme\['([\w-]+)'\]/g)]
    .map(([, k, v]) => `| \`${k}\` | \`theme['${v}']\` |`);

  /* Keys are bare identifiers or quoted when they contain a dash, and each
     tier block closes at two-space indentation. */
  const tiers = [];
  const pkgBlock = packages.match(/export const packages\s*=\s*\{([\s\S]*?)\n\};/)?.[1] || '';
  for (const m of pkgBlock.matchAll(/^\s{2}'?([\w-]+)'?:\s*\{([\s\S]*?)^\s{2}\},/gm)) {
    const [, slug, body] = m;
    const f = (k) => body.match(new RegExp(`\\b${k}:\\s*([^,\\n]+)`))?.[1]?.trim().replace(/['"]/g, '') || '—';
    if (f('icon') === '—' && f('packageColor') === '—') continue;
    tiers.push(`| \`${slug}\` | \`${f('icon')}\` | \`${f('packageColor')}\` | \`${f('textColor')}\` |`);
  }

  const brand = tenantStatics.match(/brandColor:\s*([^,\n]+)/)?.[1]?.trim() || '—';

  write('colours.md', banner('Colour maps resolved at runtime',
    [`src/tenant/common/data/staticLists.js`, `src/tenant/${TENANT}/data/packages.js`,
     `src/tenant/${TENANT}/data/staticLists.js`]) + `
None of these is a theme token. Each is a lookup the product performs against a
string the API supplies, which is why reading \`foundations.md\` alone leaves them
looking like gaps.

## Profile completion ring

\`tenantData.getClassificationColor(user.profile_completion.classification)\`.
The classification word comes from the API; the mapping does not.

| classification | colour |
|---|---|
${classification.join('\n') || '| — | not found |'}

## Package tiers

\`tenantData.packages[tenantData.slugToType[slug]]\`. Drives the plan badge in
Credits Balance.

| tier | icon | packageColor | textColor |
|---|---|---|---|
${tiers.join('\n') || '| — | — | — | not found |'}

## Platform brand colour

\`platformList[].brandColor\` = \`${brand}\`

This is the accent behind the chart line, the credit meter and the tab ink bar.
For **${TENANT}** it is not API-supplied — it resolves to the primary colour.
(zameen hardcodes its own per platform; ${TENANT} does not.)
`);
}

/* ═══ 2 · the utility scales ═══════════════════════════════════════════════
   What .p-16 and .fz-13 actually generate. Guessing a step that is not on the
   scale is how a design ends up using spacing the product cannot express. */
{
  const utils = read('src/static/less/utils.less');
  const numList = utils.match(/@numList:\s*([^;]+);/)?.[1]?.trim() || '';
  const spacers = utils.match(/@themeSpacers:\s*([^;]+);/)?.[1]?.trim() || '';
  const sizes = utils.match(/@fontSizes:\s*([^;]+);/)?.[1]?.trim() || '';
  /* Most weights are declared as a selector list — `.fw-500, .fw-medium { }` —
     so match the whole rule and keep the aliases. */
  const weights = [...utils.matchAll(/((?:\.[\w-]+,\s*)*\.fw-(\d+)[^{]*)\{\s*font-weight:\s*(\d+)/g)]
    .map(([, sel, cls, val]) => {
      const aliases = sel.trim().replace(/\s+/g, ' ').replace(/,$/, '');
      const note = cls !== val
        ? ' — **the class name and the value disagree; mirror it, do not correct it**'
        : '';
      return `| \`${aliases}\` | ${val}${note} |`;
    });

  write('scales.md', banner('The utility scales', ['src/static/less/utils.less']) + `
These are the only steps the product can express with a class. A value that is
not here has to be written as a literal in a component, and most are not.

## Spacing — \`.p-\` \`.px-\` \`.py-\` \`.m-\` \`.mt-\` \`.mb-\` \`.my-\`

\`\`\`
${numList}
\`\`\`

Plus, for \`.mt-\` \`.mb-\` \`.pb-\` only:

\`\`\`
${spacers}
\`\`\`

Every one emits \`!important\`. \`0\` emits a bare \`0\`, the rest \`n * 1px\`.

## Font size — \`.fz-\` and \`.fs\`

\`\`\`
${sizes}
\`\`\`

No \`!important\`. \`.fz-16\` is \`font-size: 16px\`.

## Font weight

| class | emits |
|---|---|
${weights.join('\n') || '| — | not found |'}
`);
}

/* ═══ 3 · the listing table ════════════════════════════════════════════════
   Columns, dispositions and which action is enabled when. All of it is data,
   and all of it was invented by eye before this. */
{
  const util = read(`src/tenant/${TENANT}/utils/listingUtilities.js`);

  const cols = [];
  const active = util.match(/case 'active':\s*return \[([\s\S]*?)\n\s{6}\];/)?.[1] || '';
  for (const m of active.matchAll(/title:\s*'([^']+)'[\s\S]{0,220}?component:\s*'(\w+)'/g)) {
    const seg = active.slice(m.index, m.index + 320);
    const w = seg.match(/width:\s*(\d+)/)?.[1];
    const fixed = /fixed:\s*'right'/.test(seg) ? 'right' : '';
    cols.push(`| ${cols.length + 1} | **${m[1]}** | \`${m[2]}\` | ${w ? w + 'px' : '—'} | ${fixed || '—'} |`);
  }

  const disp = [];
  for (const m of util.matchAll(/case '([\w-]+)':\s*\n\s*(?:\/\/[^\n]*\n\s*)?return\s*\{[\s\S]{0,200}?color:\s*'([^']*)'/g))
    disp.push(`| \`${m[1]}\` | ${m[2] ? `\`${m[2]}\`` : '_(neutral grey)_'} |`);

  const gate = (name) => {
    const block = util.match(new RegExp(`${name}\\s*=\\s*\\{([\\s\\S]*?)\\n\\}`))?.[1] || '';
    return [...block.matchAll(/'?([\w-]+)'?:\s*\[([^\]]*)\]/g)]
      .map(([, k, v]) => `| \`${k}\` | ${v.replace(/['\s]/g, '').split(',').filter(Boolean).map((x) => `\`${x}\``).join(' ') || '—'} |`);
  };

  write('listing-table.md', banner('The listings table',
    [`src/tenant/${TENANT}/utils/listingUtilities.js`,
     'src/components/table/table-actions/table-actions.js',
     'src/components/table/table-components/listing-purpose.js']) + `
## Columns — disposition \`active\`

\`listingTableColumnMapper(user, 'active')\`. **Timeline** appears only for an
\`isCurrencyUser\`.

| # | header | component | width | fixed |
|---|---|---|---|---|
${cols.join('\n') || '| — | — | — | — | not found |'}

## Status — disposition to Tag colour

\`listingDispositionMapper\`. The **label is API copy**; only the colour is local,
and it is a colour *name*, never a hex — the Tag presets in
\`components/common/tag/styled.js\` resolve it.

| disposition | Tag colour |
|---|---|
${disp.join('\n') || '| — | not found |'}

## Which upgrade is enabled when

\`dispositionDependentPlatformActions\`.

| action | enabled for |
|---|---|
${gate('dispositionDependentPlatformActions').join('\n') || '| — | not found |'}

## Which row action is enabled when

\`dispositionDependentRowActions\`.

| action | enabled for |
|---|---|
${gate('dispositionDependentRowActions').join('\n') || '| — | not found |'}

## The Property cell

\`<Group template="106px 1fr" gap=".571rem">\` — a **106px square** thumbnail at
radius 6 with \`object-fit: cover\`, then the text column. The numbered green
badge **counts the listing's images**: antd \`Badge\`, \`shape="square"\`,
\`overflowCount={90}\`, ground \`#00a651\` hardcoded.
`);
}

/* ═══ 4 · the fonts ════════════════════════════════════════════════════════
   The one question that changes every glyph on every screen. */
{
  const init = read('src/hooks/useAppInit.js');
  const injected = [...init.matchAll(/\.href\s*=\s*`?\/profolio-assets\/\$\{?[\w.]+\}?\/fonts\/([\w-]+\.css)`?/g)]
    .map((m) => m[1]);
  const latoCss = read(`public/profolio-assets/${TENANT}/fonts/lato-font.css`);
  const faces = [...latoCss.matchAll(/font-family:\s*"([^"]+)"[\s\S]*?url\('([^']+)'\)[\s\S]*?font-weight:\s*(\d+)/g)]
    .map(([, fam, file, w]) => `| ${fam} | ${w} | \`${file}\` |`);

  write('fonts.md', banner('Which fonts actually load',
    ['src/hooks/useAppInit.js', `public/profolio-assets/${TENANT}/fonts/`]) + `
\`src/theme/index.js\` names **two** stacks: \`theme['font-family']\` is Lato and the
antd v5 token \`fontFamily\` is Figtree. Only one of them is ever fetched.

\`useAppInit.js\` injects these at runtime:

${injected.map((f) => `- \`/profolio-assets/${TENANT}/fonts/${f}\``).join('\n') || '- none found'}

**Nothing anywhere loads Figtree.** Lato is what paints.

## The faces that ship

| family | weight | file |
|---|---|---|
${faces.join('\n') || '| — | — | not found |'}

**Three weights, not nine.** \`.fw-500\` and \`.fw-600\` are everywhere in the
product and neither has a real face: the browser synthesises them from Regular.
A design that asks for a true 500 or 600 will look heavier than the live screen.

## The currency mark

\`currency-font.css\` is an **icomoon glyph font**, keyed on \`[class^="currency-"]\`.
ر.س is an icon, not Arabic text — which is why it sits left of the number in an
LTR row without any bidi handling.
`);
}

/* ── report ────────────────────────────────────────────────────────────── */
for (const [name, bytes] of written) console.log(`  references/data/${name.padEnd(20)} ${(bytes / 1024).toFixed(1)}KB`);
console.log(`  ${written.length} files, ~${Math.round(written.reduce((a, [, b]) => a + b, 0) / 4)} tokens if all were read at once`);
