#!/usr/bin/env node
/**
 * Embeds the product's own font files.
 *
 * The deliverables were loading Lato 300/400/700/900 from Google Fonts. Two
 * things were wrong with that. The product self-hosts three woff2 files and
 * injects them at runtime (src/hooks/useAppInit.js pulls
 * /profolio-assets/<tenant>/fonts/lato-font.css), and it ships only Light,
 * Regular and Bold — so every .fw-500 and .fw-600 on the live screen is a
 * weight the browser synthesises, not a real face. Asking Google for a real 500
 * or 900 makes the type look *better* than production, which is the wrong kind
 * of wrong for a reference.
 *
 * This copies the exact files into deliverables/fonts.css as base64, so the
 * deliverables match the product glyph for glyph and need no network at all.
 *
 *   node scripts/fonts.mjs --repo ../profolio-reactjs-copy --tenant bayut
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const arg = (n, d) => { const i = process.argv.indexOf(n); return i > -1 ? process.argv[i + 1] : d; };
const REPO = join(ROOT, arg('--repo', '../profolio-reactjs-copy'));
const TENANT = arg('--tenant', 'bayut');
const DIR = join(REPO, 'public', 'profolio-assets', TENANT, 'fonts');

/* Mirrors lato-font.css and arabic-font.css in that directory. Arabic is here
   because the stack names it second and an Arabic string falls through to it;
   the English-first deliverables rarely hit it, but leaving it out would make
   any Arabic text render in a system fallback instead. */
const FACES = [
  { file: 'Lato-Light.woff2',        family: 'Lato',               weight: 300 },
  { file: 'Lato-Regular.woff2',      family: 'Lato',               weight: 400 },
  { file: 'Lato-Bold.woff2',         family: 'Lato',               weight: 700 },
  { file: 'DroidArabicKufi.woff2',   family: 'Droid Arabic Kufi',  weight: 400 },
];

const out = [];
const missing = [];
let bytes = 0;

for (const f of FACES) {
  const p = join(DIR, f.file);
  if (!existsSync(p)) { missing.push(f.file); continue; }
  const buf = readFileSync(p);
  bytes += buf.length;
  out.push(
    `@font-face{\n` +
    `  font-family:"${f.family}";\n` +
    `  src:url(data:font/woff2;base64,${buf.toString('base64')}) format("woff2");\n` +
    `  font-weight:${f.weight};\n` +
    `  font-style:normal;\n` +
    `  font-display:swap;\n` +
    `}`
  );
}

const css =
`/* GENERATED by scripts/fonts.mjs — do not edit.
   The tenant's own font files, embedded from
   public/profolio-assets/${TENANT}/fonts/, so the deliverables use the same
   faces the product does and need no network.

   Only three Lato weights exist: 300, 400 and 700. That is deliberate and it
   matches production — every .fw-500 and .fw-600 in the product is synthesised
   by the browser from Regular, and the deliverables must do the same or the
   type reads heavier than the real screen. Do not add weights here. */
${out.join('\n')}
`;

writeFileSync(join(ROOT, 'deliverables', 'fonts.css'), css);
console.log(`  deliverables/fonts.css — ${out.length} faces, ${(bytes / 1024).toFixed(0)}KB source → ${(css.length / 1024).toFixed(0)}KB base64`);
if (missing.length) console.log(`  ! not found in ${DIR}: ${missing.join(', ')}`);
